defaultProject: ken-e-production
defaultLocation: US
defaultDataset: a00000X
defaultAssertionDataset: a00000X_assertions
datasetSuffix: sample_client
vars:
    datasetStaging: "a00000X_staging"
    datasetOutput: "a00000X"
    datasetExtras: "a00000X_extras"
    ga4SourceDatabase: "<CLIENT_SOURCE_PROJECT>"
    ga4SourceDataset: "google_analytics"
    ga4ReportingIdentity: "observed"
    ga4DaysBack: "3"
    ga4StartDate: "2020-01-01"
    ga4IncludeIntraday: "false"
    ga4Timezone: "America/New_York"
    ga4UnwantedReferrals: "00000000.com,test.com"